name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: set release date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
        
    - uses: actions/checkout@v3
    - name: login
      run: docker login ${{secrets.AZURE_LOGIN}} -u ${{secrets.AZURE_USERNAME}} -p ${{secrets.AZURE_PASSWORD}}
    - name: build image
      run: docker build -t ${{secrets.AZURE_LOGIN}}/fastapi:${env.RELEASE_DATE} .
      
    - name: push image
      run: docker push ${{secrets.AZURE_LOGIN}}/fastapi:${env.RELEASE_DATE}
