name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      run: |
        echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - id: version
    - uses: actions/checkout@v3
    - name: login
      run: docker login ${{secrets.AZURE_LOGIN}} -u ${{secrets.AZURE_USERNAME}} -p ${{secrets.AZURE_PASSWORD}}
    - name: build image
      run: docker build -t ${{secrets.AZURE_LOGIN}}/fastapi:${steps.version.outputs.builddate} .
      
    - name: push image
      run: docker push ${{secrets.AZURE_LOGIN}}/fastapi:${steps.version.outputs.builddate}
